# Generate API docs using doxygen, and deploy the results using github pages

name: Generate and deploy API docs to Github Pages

on:
  push:
    branches: [master]
    paths:
      - Doxyfile
      - include/pg2sdr.h

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Install doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends doxygen graphviz
      - name: Generate docs via doxygen
        run: |
          doxygen
      - name: Upload doxygen output
        uses: actions/upload-pages-artifact@v5
        with:
          path: './doc/html'

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
