name: Build Debian packages

on:
  workflow_dispatch:
    inputs:
      build-environment:
        type: string
        default: dev

jobs:
  build-packages:
    name: Build ${{ inputs.dist }}-${{ inputs.arch }} packages
    runs-on:
    runs-on:
      - debian-builder
      - ${{ matrix.dist }}-${{ matrix.arch }}
    strategy:
      matrix:
        dist:
          - trixie
        arch:
          - armhf
          - arm64
      fail-fast: false

    env:
      DIST: ${{ matrix.dist }}
      ARCH: ${{ matrix.arch }}
      BUILDENVIRONMENT: ${{ inputs.build-environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare environment vars
        run: |
          echo "ARTIFACT=debian-packages-$DIST-$ARCH" >>$GITHUB_ENV
          echo "BUILDDIR=${{ runner.temp }}/build-$DIST-$ARCH" >>$GITHUB_ENV
          echo "RESULTDIR=${{ runner.temp }}/results-$DIST-$ARCH" >>$GITHUB_ENV
      - name: Prepare copy of build tree
        run: |
          rm -fr "$BUILDDIR"
          cp -a pg2sdr-firmware "$BUILDDIR"
      - name: Build package
        run: |
          rm -fr "$RESULTDIR"
          mkdir "$RESULTDIR"
          cd "$BUILDDIR"
          pdebuild --use-pdebuild-internal --debbuildopts -b --buildresult "$RESULTDIR" -- --override-config
      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.RESULTDIR }}/*.deb
